IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'CISDB')
BEGIN
  CREATE DATABASE CISDB;
END;

ALTER DATABASE CISDB  
SET ALLOW_SNAPSHOT_ISOLATION ON  
  
ALTER DATABASE CISDB  
SET READ_COMMITTED_SNAPSHOT ON
